---
name: Docker Image Build
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: nolte
      IMAGE_NAME: mopidy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.0.0
        with:
          buildx-version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push container image
        run: |
          docker buildx build \
            -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:dirty" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7 \
            -f Dockerfile \
            .
