---
name: Docker Image CI
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAMESPACE: nolte
      IMAGE_NAME: mopidy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
        with:
          buildx-version: latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Determine tag
        id: imagetag
        run: |
          echo "::set-output name=image_tag::${GITHUB_REF#refs/tags/}"

      - name: Build and push container image
        run: |
          docker buildx build \
            -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:latest" \
            -t "${IMAGE_NAMESPACE}/${IMAGE_NAME}:${{ steps.imagetag.outputs.image_tag }}" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7 \
            --push \
            -f Dockerfile \
            .
